# Generated by Django 3.1.14 on 2023-05-03 23:18

from django.db import migrations, models

import ob_dj_feature_flags.utils.model


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the flag", max_length=10, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the flag", null=True
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=False, help_text="Whether the flag is active or not"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the flag was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the flag was last updated"
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Flag",
                "verbose_name_plural": "Feature Flags",
            },
            bases=(
                ob_dj_feature_flags.utils.model.DjangoModelCleanMixin,
                models.Model,
            ),
        ),
    ]
