version: '3.3'

services:
  app: &app
    build: .
    env_file:
      - docker-compose.env
      - docker-compose.local.env
    depends_on:
      - migrate

    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      bash -c "python manage.py runserver 0.0.0.0:8000"

  migrate:
    <<: *app
    command: >
      bash -c "python manage.py migrate"
    ports: []
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
    tmpfs:
      - /var/lib/postgresql/data
    ports:
     - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
